src/Entity/Habitat.php
<?php

namespace App\Entity;

use App\Repository\HabitatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HabitatRepository::class)]
class Habitat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $commentaireHabitat = null;

    /**
     * @var Collection<int, Animal>
     */
    #[ORM\OneToMany(targetEntity: Animal::class, mappedBy: 'habitat', orphanRemoval: true)]
    private Collection $animals;

    #[ORM\Column(length: 255)]
    private ?string $image = null; 

    public function __construct()
    {
        $this->animals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCommentaireHabitat(): ?string
    {
        return $this->commentaireHabitat;
    }

    public function setCommentaireHabitat(string $commentaireHabitat): static
    {
        $this->commentaireHabitat = $commentaireHabitat;

        return $this;
    }

    /**
     * @return Collection<int, Animal>
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    public function addAnimal(Animal $animal): static
    {
        if (!$this->animals->contains($animal)) {
            $this->animals->add($animal);
            $animal->setHabitat($this);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): static
    {
        if ($this->animals->removeElement($animal)) {
            // set the owning side to null (unless already changed)
            if ($animal->getHabitat() === $this) {
                $animal->setHabitat(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

   /*  public function getRace(): Race 
    {
        return $this->getAnimal()->getRace();
    }

    public function getRaceLabel(): string
    {
        return $this->getRace()->getLabel();
    } */
}

src/Entity/RapportVeterinaire.php
<?php

namespace App\Entity;

use App\Repository\RapportVeterinaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RapportVeterinaireRepository::class)]
#[ORM\HasLifecycleCallbacks] // Permet d'utiliser les callbacks PrePersist et PreUpdate
class RapportVeterinaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $detail = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'rapportVeterinaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $user = null;

    #[ORM\ManyToOne(inversedBy: 'rapportVeterinaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Animal $animal = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Etat = null;

    #[ORM\Column(length: 255)]
    private ?string $nourriture = null;

    #[ORM\Column]
    private ?int $Gramage = null; 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function setAnimal(?Animal $animal): static 
    {
        $this->animal = $animal;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): static
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getNourriture(): ?string
    {
        return $this->nourriture;
    }

    public function setNourriture(string $nourriture): static
    {
        $this->nourriture = $nourriture;

        return $this;
    }

    public function getGramage(): ?int
    {
        return $this->Gramage;
    }

    public function setGramage(int $Gramage): static
    {
        $this->Gramage = $Gramage;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getRace(): Race 
    {
        return $this->getAnimal()->getRace();
    }

    public function getRaceLabel(): string
    {
        return $this->getRace()->getLabel();
    }
}

templates/admin_animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les habitats du zoo{% endblock %}

{% block content %}

<div class="text-center m-4">
    <h1>Les habitats du zoo Arcadia</h1>

    <div class="container">
        <div class="row">
        {% for habitat in habitats %}
            <div class="col-12 col-md-6 col-lg-4 p-2">
                <div class="card">
                    <img src="{{ asset('uploads/habitats/images/' ~ habitat.image) }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <a href="{{ path('app_admin_habitat_show', {id: habitat.id}) }}" class="mb-1 h4 text-decoration-none">{{ habitat.nom }}</a>
                            {# <a href="{{ path('app_admin_habitat_show', {id: habitat.id}) }}" class="btn bg_primary text-white m-2">Voir les animaux des {{ habitat.nom }}</a> #} 
                        </div>
                </div>
            </div>
                {% else %}
                <p>Aucun enregistrement en base de données.</p> 
            {% endfor %}
        </div>
    </div>

    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_EMPLOYEE') %}
    <div>
        <a class="btn bg_primary text-white m-4" href="habitat/new">Ajouter un nouvel habitat</a>
    </div>
    {% endif %}

</div>
{% endblock %} 

templates/admin_animal/new.html.twig
{% extends 'base.html.twig' %}

{% set action = app.current_route == 'app_admin_animal_new' ? 'Ajout' : 'Édition' %}

{% block title %}{{ action }} d'animaux{% endblock %}

{% block content %}

    <div class="w-50 m-auto">
        <div class="example-wrapper">
            <h1 class="d-flex justify-content-center">Ajout d'un nouvel animal</h1>
                
                    {{ form_start(form, {'attr': {'enctype': 'multipart/form-data'}}) }}
                        {{ form_row(form.prenom, {label: 'Prénom de l\'animal'}) }}
                        {{ form_row(form.race, {label: 'Race de l\'animal'}) }}
                        {{ form_row(form.habitat, {label: 'Habitat de l\'animal'}) }}
                        {{ form_row(form.habitatReel, {label: 'Nom spécifique de l\'habitat'}) }}
                        {{ form_row(form.etat, {label: 'État général de l\'animal'}) }}
                        {{ form_row(form.nourritureGlobale, {label: 'Nourriture de l\'animal'}) }}
                         {{ form_row(form.image) }}
                        {{ form_row(form.confirmation) }}
                    {{ form_widget(form) }}
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn bg_primary text-white">Valider</button>
                    </div>
                    {{ form_end(form) }}
                 
           
        </div>
    </div>
{% endblock %}

templates/admin_animal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les habitats du zoo{% endblock %}

{% block content %}



{% endblock %} 