src/Entity/RapportVeterinaire.php
<?php

namespace App\Entity;

use App\Repository\RapportVeterinaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RapportVeterinaireRepository::class)]
#[ORM\HasLifecycleCallbacks] // Permet d'utiliser les callbacks PrePersist et PreUpdate
class RapportVeterinaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $detail = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'rapportVeterinaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $user = null;

    #[ORM\ManyToOne(inversedBy: 'rapportVeterinaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Animal $animal = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Etat = null;

    #[ORM\Column(length: 255)]
    private ?string $nourriture = null;

    #[ORM\Column]
    private ?int $Gramage = null; 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function setAnimal(?Animal $animal): static 
    {
        $this->animal = $animal;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): static
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getNourriture(): ?string
    {
        return $this->nourriture;
    }

    public function setNourriture(string $nourriture): static
    {
        $this->nourriture = $nourriture;

        return $this;
    }

    public function getGramage(): ?int
    {
        return $this->Gramage;
    }

    public function setGramage(int $Gramage): static
    {
        $this->Gramage = $Gramage;

        return $this;
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getRace(): Race 
    {
        return $this->getAnimal()->getRace();
    }

    public function getRaceLabel(): string
    {
        return $this->getRace()->getLabel();
    }
}

src/Controller/RapportVetController.php
<?php

namespace App\Controller;

use App\Entity\RapportVeterinaire;
use App\Form\RapportFormType;
use App\Repository\RapportVeterinaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/rapport-vet')]
class RapportVetController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    
    #[Route('', name: 'app_admin_rapport_index', methods: ['GET'])]
    public function index(RapportVeterinaireRepository $repository): Response
    {
        if (!$this->isGranted('ROLE_ADMIN') && !$this->isGranted('ROLE_VETO')) {
            throw new AccessDeniedException('Vous n\'avez pas les droits pour accéder à cette page.');
        }

        $rapportveterinaires = $repository->findBy([], ['createdAt' => 'DESC']);

        return $this->render('rapport_vet/index.html.twig', [
            'controller_name' => 'RapportVetController',
            'rapportveterinaires' => $rapportveterinaires,
        ]);
    }

    #[Route('/new', name: 'app_admin_rapport_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_VETO')]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $user = $this->security->getUser();

        $rapportveterinaire = new RapportVeterinaire();
        $rapportveterinaire->setUser($user);
        $form = $this->createForm(RapportFormType::class, $rapportveterinaire);
    

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

        $manager->persist($rapportveterinaire);
        $manager->flush(); 

        return $this->redirectToRoute('app_admin_rapport_index', ['id' => $rapportveterinaire->getId()]);
        }

        return $this->render('rapport_vet/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/delete/{id}', name: 'app_admin_rapport_delete', methods: ['POST', 'DELETE'])] //La méthode POST supprime l'élément, mais pas la méthode DELETE...
    #[IsGranted('ROLE_VETO')]
    public function delete(RapportVeterinaire $rapportveterinaire, EntityManagerInterface $entityManager, Request $request): Response
    {
        // Vérification du token CSRF pour sécuriser la suppression
        if ($this->isCsrfTokenValid('delete'.$rapportveterinaire->getId(), $request->request->get('_token'))) {
            $entityManager->remove($rapportveterinaire);
            $entityManager->flush();

            $this->addFlash('success', 'Rapport supprimé avec succès.');
        } else {
            $this->addFlash('error', 'Échec de la suppression du rapport.');
        }

        return $this->redirectToRoute('app_admin_rapport_index'); // Redirection vers la liste des services ou autre page
    }
}

templates/rapport_vet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rapports Vétérinaires{% endblock %}

{% block content %}


<div class="text-center m-4">
    <h1>Rapports Vétérinaires</h1>
</div>

 <div class="container">
        <div class="row bg_dark text-white text-center">
        {% for rapportveterinaire in rapportveterinaires %}
            <li class="row border-bottom">
                <div class="col">
                    <p>{{ rapportveterinaire.date|date('d/m/Y') }} -- {{ rapportveterinaire.animal }}</p>
                </div>
                <div class="col">
                    <button class="btn bg_primary text-white mt-2" type="button" data-bs-toggle="modal" data-bs-target="#rapportVet-modal-{{ rapportveterinaire.id }}">Ouvrir</button>
                </div>
        

        <!-- Modal -->
                <div class="modal fade text-black" id="rapportVet-modal-{{ rapportveterinaire.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        <div class="modal-header row">
                            <h1 class="col modal-title fs-5 text-center" id="exampleModalLabel"> {{ rapportveterinaire.date|date('d/m/Y') }} -- {{ rapportveterinaire.animal }}</h1>
                            <h4 class="col modal-title fs-5 text-center">Rédigé par {{ rapportveterinaire.user.prenom }}</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body text-start col">
                            <div class="row">
                                Race : {{ rapportveterinaire.getRaceLabel }}
                            </div>
                            <div class="row">
                                Prénom de l'animal : {{ rapportveterinaire.animal }}
                            </div>
                            <div class="row">
                                État général : {{ rapportveterinaire.etat }}
                            </div>
                            <div class="row">
                                Nourriture donnée : {{ rapportveterinaire.nourriture }}
                                Quantité : {{ rapportveterinaire.gramage }} gr
                            </div>
                            <div class="row">
                                Informations détaillées : {{ rapportveterinaire.detail }}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                            
                        </div>
                        </div>
                    </div>
                </div>
            </li>


                {% else %}
                <p>Aucun enregistrement en base de données.</p> 
            {% endfor %}
        </div>
    </div>






{% endblock %} 

templates/rapport_vet/item.html.twig
<li class="row border-bottom">
    <div class="col">
        <p>{{ rapportveterinaire.date|date('d/m/Y') }} -- {{ rapportveterinaire.animal }}</p>
    </div>
    <div class="col">
        <button class="btn bg_primary text-white mt-2" type="button" data-bs-toggle="modal" data-bs-target="#rapportVet-modal-{{ rapportveterinaire.id }}">Ouvrir</button>
    </div>
        

        <!-- Modal -->
        <div class="modal fade text-black" id="rapportVet-modal-{{ rapportveterinaire.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header row">
                        <h1 class="col modal-title fs-5 text-center" id="exampleModalLabel"> {{ rapportveterinaire.date|date('d/m/Y') }} -- {{ rapportveterinaire.animal }}</h1>
                        <h4 class="col modal-title fs-5 text-center">Rédigé par {{ rapportveterinaire.user.prenom }}</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-start col">
                        <div class="row">
                            Race : {{ rapportveterinaire.getRaceLabel }}
                        </div>
                        <div class="row">
                            Prénom de l'animal : {{ rapportveterinaire.animal }}
                        </div>
                        <div class="row">
                            État général : {{ rapportveterinaire.etat }}
                        </div>
                        <div class="row">
                            Nourriture donnée : {{ rapportveterinaire.nourriture }}
                            Quantité : {{ rapportveterinaire.gramage }} gr
                        </div>
                        <div class="row">
                            Informations détaillées : {{ rapportveterinaire.detail }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                        
                    </div>
                </div>
            </div>
        </div>
    
</li>

templates/rapport_vet/new.html.twig
{% extends 'base.html.twig' %}

{% set action = app.current_route == 'app_admin_rapport_new' ? 'Ajout' : 'Édition' %}

{% block title %}{{ action }} de rapport vétérinaire{% endblock %}

{% block content %}

<div class="w-50 m-auto m-4">
    <div class="example-wrapper">
        <h1 class="d-flex justify-content-center">Nouveau Rapport Vétérinaire</h1> 
            {{ form_start(form, {'attr': {'enctype': 'multipart/form-data'}}) }}
                {{ form_row(form.animal, {label: 'Animal'}) }}
                {{ form_row(form.etat, {label: 'État général'}) }}
                {{ form_row(form.nourriture, {label: 'Nourriture'}) }}
                {{ form_row(form.gramage, {label: 'Gramage'}) }}
                {{ form_row(form.date, {label: 'Date de passage'}) }}
                {{ form_row(form.detail, {label: 'Détails sur l\'état de l\'animal'}) }}
                {{ form_row(form.confirmation) }}
            {{ form_widget(form) }}
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn bg_primary text-white">Valider</button>
            </div>
            {{ form_end(form) }}
    </div>
</div>
{% endblock %}